"""empty message

Revision ID: 83a3580eb46f
Revises: 454b3424207e
Create Date: 2021-03-13 13:56:48.941920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83a3580eb46f'
down_revision = '454b3424207e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('show_venue')
    op.drop_table('show_artist')
    op.add_column('Show', sa.Column('artist_id', sa.Integer(), nullable=False))
    op.add_column('Show', sa.Column('venue_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Show', 'Venue', ['venue_id'], ['id'])
    op.create_foreign_key(None, 'Show', 'Artist', ['artist_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Show', type_='foreignkey')
    op.drop_constraint(None, 'Show', type_='foreignkey')
    op.drop_column('Show', 'venue_id')
    op.drop_column('Show', 'artist_id')
    op.create_table('show_artist',
    sa.Column('show_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], name='show_artist_artist_id_fkey'),
    sa.ForeignKeyConstraint(['show_id'], ['Show.id'], name='show_artist_show_id_fkey'),
    sa.PrimaryKeyConstraint('show_id', 'artist_id', name='show_artist_pkey')
    )
    op.create_table('show_venue',
    sa.Column('show_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['show_id'], ['Show.id'], name='show_venue_show_id_fkey'),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], name='show_venue_venue_id_fkey'),
    sa.PrimaryKeyConstraint('show_id', 'venue_id', name='show_venue_pkey')
    )
    # ### end Alembic commands ###
